name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[BUG] "
labels: ["bug"]
assignees: "iamsrikanthnani"
body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 Bug Report

        **Before submitting:**
        - [x] I have searched for similar issues and didn't find a duplicate
        - [x] I have tried the latest version of Pluely

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which operating system are you using?
      options:
        - macOS
        - Windows
        - Linux
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Pluely Version
      description: What version of Pluely are you using?
      placeholder: "e.g., 0.1.3"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe the bug in detail
      placeholder: "Describe the issue you're experiencing..."
    validations:
      required: true
