name: ❓ General Issue
description: For questions, discussions, or issues that don't fit other categories
title: "[GENERAL] "
labels: ["question"]
assignees: "iamsrikanthnani"
body:
  - type: markdown
    attributes:
      value: |
        ## ❓ General Issue

        **Before submitting:**
        - [x] I have searched for similar issues and didn't find a duplicate
        - [x] I have read the README and documentation
        - [x] I have searched for similar questions/issues

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe your question or issue
      placeholder: "Describe what you need help with..."
    validations:
      required: true
